apiVersion: v1
kind: Service
metadata:
  name: video-ingestion-service
spec:
  selector:
    app: video-ingestion-app  # Must match labels in deployment.yaml.
  ports:
    - protocol: TCP
      port: 80  # External port to expose.
      targetPort: 8080  # Port inside your container.
  type: LoadBalancer  # This will expose your service externally.